import { FrameData, JunctionState, LinkState, VehicleState } from "./types";

export function createDefaultFrame(): FrameData {
  const junctions: Record<string, JunctionState> = {
    J1: {
      id: "J1",
      name: "Clock Tower",
      world_x: 100.0,
      world_y: 100.0,
      phase: "NS_GREEN",
      axis: "NS",
      is_green: true,
      is_yellow: false,
      is_all_red: false,
      time_remaining_s: 24,
      target_duration_s: 35,
      ns_green_target: 35,
      ew_green_target: 30,
      plan_desc: "QAOA Optimal Split (NS Favored)",
      reason: "Platoon progression aligned with J3",
      is_preempted: false,
      preempt_axis: null,
      queues: { N: 3, S: 2, E: 1, W: 1 },
      pedestrians: {},
      safety_status: "NOMINAL",
    },
    J2: {
      id: "J2",
      name: "Market Circle",
      world_x: 320.0,
      world_y: 100.0,
      phase: "NS_GREEN",
      axis: "NS",
      is_green: true,
      is_yellow: false,
      is_all_red: false,
      time_remaining_s: 21,
      target_duration_s: 35,
      ns_green_target: 35,
      ew_green_target: 30,
      plan_desc: "Coordinated East Approach",
      reason: "Arterial progression from J1",
      is_preempted: false,
      preempt_axis: null,
      queues: { N: 2, S: 3, E: 2, W: 1 },
      pedestrians: {},
      safety_status: "NOMINAL",
    },
    J3: {
      id: "J3",
      name: "Hospital Gate",
      world_x: 100.0,
      world_y: 300.0,
      phase: "EW_GREEN",
      axis: "EW",
      is_green: true,
      is_yellow: false,
      is_all_red: false,
      time_remaining_s: 18,
      target_duration_s: 30,
      ns_green_target: 30,
      ew_green_target: 35,
      plan_desc: "Hospital Corridor Buffer",
      reason: "Corridor clearance readiness",
      is_preempted: false,
      preempt_axis: null,
      queues: { N: 1, S: 1, E: 3, W: 2 },
      pedestrians: {},
      safety_status: "NOMINAL",
    },
    J4: {
      id: "J4",
      name: "Bus Stand",
      world_x: 320.0,
      world_y: 300.0,
      phase: "EW_GREEN",
      axis: "EW",
      is_green: true,
      is_yellow: false,
      is_all_red: false,
      time_remaining_s: 16,
      target_duration_s: 30,
      ns_green_target: 30,
      ew_green_target: 35,
      plan_desc: "Underpass Feeder Balanced",
      reason: "Bus egress synchronization",
      is_preempted: false,
      preempt_axis: null,
      queues: { N: 2, S: 1, E: 2, W: 3 },
      pedestrians: {},
      safety_status: "NOMINAL",
    },
  };

  const links: LinkState[] = [
    {
      id: "L_J1_J2",
      from: "J1",
      to: "J2",
      length_m: 220.0,
      lanes: 3,
      speed_limit_mps: 14.0,
      capacity_vph: 2400,
      is_arterial: true,
      is_underpass: false,
      is_narrow: false,
      is_closed: false,
      has_accident: false,
      is_flooded: false,
      status: "OPEN",
      effective_capacity: 2400,
      tag: "North Arterial",
    },
    {
      id: "L_J2_J1",
      from: "J2",
      to: "J1",
      length_m: 220.0,
      lanes: 3,
      speed_limit_mps: 14.0,
      capacity_vph: 2400,
      is_arterial: true,
      is_underpass: false,
      is_narrow: false,
      is_closed: false,
      has_accident: false,
      is_flooded: false,
      status: "OPEN",
      effective_capacity: 2400,
      tag: "North Arterial WB",
    },
    {
      id: "L_J2_J4",
      from: "J2",
      to: "J4",
      length_m: 200.0,
      lanes: 2,
      speed_limit_mps: 11.0,
      capacity_vph: 1600,
      is_arterial: false,
      is_underpass: false,
      is_narrow: false,
      is_closed: false,
      has_accident: false,
      is_flooded: false,
      status: "OPEN",
      effective_capacity: 1600,
      tag: "East Connector",
    },
    {
      id: "L_J4_J2",
      from: "J4",
      to: "J2",
      length_m: 200.0,
      lanes: 2,
      speed_limit_mps: 11.0,
      capacity_vph: 1600,
      is_arterial: false,
      is_underpass: false,
      is_narrow: false,
      is_closed: false,
      has_accident: false,
      is_flooded: false,
      status: "OPEN",
      effective_capacity: 1600,
      tag: "East Connector NB",
    },
    {
      id: "L_J3_J4",
      from: "J3",
      to: "J4",
      length_m: 220.0,
      lanes: 2,
      speed_limit_mps: 11.0,
      capacity_vph: 1400,
      is_arterial: false,
      is_underpass: true,
      is_narrow: false,
      is_closed: false,
      has_accident: false,
      is_flooded: false,
      status: "OPEN",
      effective_capacity: 1400,
      tag: "Underpass Link",
    },
    {
      id: "L_J4_J3",
      from: "J4",
      to: "J3",
      length_m: 220.0,
      lanes: 2,
      speed_limit_mps: 11.0,
      capacity_vph: 1400,
      is_arterial: false,
      is_underpass: true,
      is_narrow: false,
      is_closed: false,
      has_accident: false,
      is_flooded: false,
      status: "OPEN",
      effective_capacity: 1400,
      tag: "Underpass Link WB",
    },
    {
      id: "L_J1_J3",
      from: "J1",
      to: "J3",
      length_m: 200.0,
      lanes: 3,
      speed_limit_mps: 14.0,
      capacity_vph: 2400,
      is_arterial: true,
      is_underpass: false,
      is_narrow: false,
      is_closed: false,
      has_accident: false,
      is_flooded: false,
      status: "OPEN",
      effective_capacity: 2400,
      tag: "West Arterial SB",
    },
    {
      id: "L_J3_J1",
      from: "J3",
      to: "J1",
      length_m: 200.0,
      lanes: 3,
      speed_limit_mps: 14.0,
      capacity_vph: 2400,
      is_arterial: true,
      is_underpass: false,
      is_narrow: false,
      is_closed: false,
      has_accident: false,
      is_flooded: false,
      status: "OPEN",
      effective_capacity: 2400,
      tag: "West Arterial NB",
    },
    // Entry / arterial feeder arms
    {
      id: "L_ENTRY_J1_N",
      from: "ENTRY_N",
      to: "J1",
      length_m: 150.0,
      lanes: 3,
      speed_limit_mps: 14.0,
      capacity_vph: 2400,
      is_arterial: true,
      is_underpass: false,
      is_narrow: false,
      is_closed: false,
      has_accident: false,
      is_flooded: false,
      status: "OPEN",
      effective_capacity: 2400,
      tag: "North Highway Ingress",
    },
    {
      id: "L_ENTRY_J1_W",
      from: "ENTRY_W",
      to: "J1",
      length_m: 140.0,
      lanes: 2,
      speed_limit_mps: 11.0,
      capacity_vph: 1600,
      is_arterial: false,
      is_underpass: false,
      is_narrow: false,
      is_closed: false,
      has_accident: false,
      is_flooded: false,
      status: "OPEN",
      effective_capacity: 1600,
      tag: "West Approach",
    },
    {
      id: "L_ENTRY_J2_E",
      from: "ENTRY_E",
      to: "J2",
      length_m: 140.0,
      lanes: 2,
      speed_limit_mps: 11.0,
      capacity_vph: 1600,
      is_arterial: false,
      is_underpass: false,
      is_narrow: false,
      is_closed: false,
      has_accident: false,
      is_flooded: false,
      status: "OPEN",
      effective_capacity: 1600,
      tag: "East Approach",
    },
    {
      id: "L_ENTRY_J4_S",
      from: "ENTRY_S",
      to: "J4",
      length_m: 150.0,
      lanes: 2,
      speed_limit_mps: 11.0,
      capacity_vph: 1600,
      is_arterial: false,
      is_underpass: false,
      is_narrow: false,
      is_closed: false,
      has_accident: false,
      is_flooded: false,
      status: "OPEN",
      effective_capacity: 1600,
      tag: "South Highway Ingress",
    },
  ];

  const vehicles: VehicleState[] = [
    { id: "v_init_1", type: "car", link: "L_J1_J2", pos: 45.0, speed: 11.5 },
    { id: "v_init_2", type: "auto", link: "L_J1_J2", pos: 120.0, speed: 9.0 },
    { id: "v_init_3", type: "two_wheeler", link: "L_J1_J3", pos: 60.0, speed: 12.0 },
    { id: "v_init_4", type: "bus", link: "L_J3_J4", pos: 80.0, speed: 8.5 },
    { id: "v_init_5", type: "car", link: "L_J2_J4", pos: 50.0, speed: 10.0 },
    { id: "v_init_6", type: "car", link: "L_J4_J3", pos: 110.0, speed: 10.5 },
  ];

  return {
    seq: 1,
    sim_time: 1.0,
    is_paused: false,
    speed: 1.0,
    weather: "CLEAR",
    fallback_level: "QUANTUM_OPTIMAL",
    corridor: {
      is_active: false,
      origin: null,
      destination: null,
      route: [],
      junction_etas: {},
      junction_axes: {},
      travel_time_hybrid: null,
      travel_time_fixed: null,
      travel_time_rule: null,
    },
    resilience_index: {
      overall: 78.4,
      breakdown: {
        queue_stability: 82.0,
        emergency_readiness: 90.0,
        network_balance: 75.0,
        spillback_protection: 76.0,
        signal_efficiency: 84.0,
      },
    },
    decision_confidence: {
      percentage: 86,
      status: "HIGH_CONFIDENCE",
      reason: "Continuous physical sensor telemetry verified across all arms",
    },
    metrics: {
      fixed: {
        avg_wait_s: 24.3,
        max_queue: 14,
        throughput: 31,
        total_fuel_l: 1.42,
        total_co2_kg: 3.28,
        avg_travel_time_s: 41.2,
      },
      rule: {
        avg_wait_s: 21.0,
        max_queue: 11,
        throughput: 34,
        total_fuel_l: 1.25,
        total_co2_kg: 2.91,
        avg_travel_time_s: 37.8,
      },
      hybrid: {
        avg_wait_s: 17.7,
        max_queue: 8,
        throughput: 38,
        total_fuel_l: 0.98,
        total_co2_kg: 2.29,
        avg_travel_time_s: 33.5,
      },
    },
    junctions,
    junctions_fixed: JSON.parse(JSON.stringify(junctions)),
    vehicles_hybrid: vehicles,
    vehicles_fixed: vehicles,
    links,
    shift_log: [
      { time: "00:01", text: "Digital twin simulation engine initialized." },
      { time: "00:01", text: "Network topology loaded: 4 junctions, 12 links." },
    ],
    solver_summary: {
      method: "QAOA_AER",
      approx_ratio: 0.92,
      wall_time_ms: 18.4,
      qubit_count: 8,
      circuit_depth: 3,
      brute_force_time_ms: 0.08,
      simulated_annealing_time_ms: 4.8,
    },
  };
}
